#!/bin/sh

BUILD_PATH=build
TOOLCHAIN_FILE=toolchain.cmake
SYSROOT=
CROSS_COMPILE= 

if [ ! $BUILD_PATH -d ]; then
    mkdir $BUILD_PATH
fi

cd $BUILD_PATH
cmake ../ -DCROSS_COMPILE=$CROSS_COMPILE -DSYSROOT=$SYSROOT -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE
